# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='person',
            field=models.ManyToManyField(blank=True, null=True, to='api.Person'),
        ),
    ]
